from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from .. import models, schemas, database

# Create a router specifically for Donor-related endpoints
router = APIRouter(
    prefix="/api/donors",
    tags=["Donors"]
)

# 1. Endpoint to CREATE a new donor (POST request)
@router.post("/", response_model=schemas.DonorResponse)
def create_donor(donor: schemas.DonorCreate, db: Session = Depends(database.get_db)):
    
    # First, check if someone with this phone number is already registered
    existing_donor = db.query(models.Donor).filter(models.Donor.phone_number == donor.phone_number).first()
    if existing_donor:
        raise HTTPException(status_code=400, detail="Phone number already registered")
    
    # If not, convert the Pydantic schema into a SQLAlchemy database model
    new_donor = models.Donor(**donor.model_dump()) 
    
    # Add it to the database and save (commit)
    db.add(new_donor)
    db.commit()
    db.refresh(new_donor) # Gets the new ID generated by the database
    
    return new_donor

# 2. Endpoint to GET all donors (GET request)
@router.get("/", response_model=list[schemas.DonorResponse])
def get_all_donors(db: Session = Depends(database.get_db)):
    donors = db.query(models.Donor).all()
    return donors